exp_dir: /home/ericxhzou/Code/PCGL-Benchmark/exp/rerank
debug: False
rerank:
  name: avgQE
  pr_backbone: PPTNet  # PPTNet / LoGG3D-Net / EgoNN
  k: 25
protocol: '/home/ericxhzou/Code/PCGL-Benchmark/config/rerank/protocol.yaml'